### DISCUSSION TITLE
【教程贴】Docker部署教程和相关问题讨论

### DISCUSSION THREAD

**Discussion by HalcyonAzure** [lsky-org/lsky-pro#373] [教程]
***注：该容器为第三方自行维护，如果出现了容器内的问题请在[这个仓库](https://github.com/HalcyonAzure/lsky-pro-docker)下提出`issues`，另外在提问前请先阅读[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)***

# Docker部署Lsky-Pro的方法

## 直接使用Docker Hub拉取使用

该镜像为自己维护的镜像，会每周拉取一次最新的代码进行构建

参考了之前 #256  里面的方法，对2.0正式版本也自己写了个Dockfile。在Dockerfile里面直接修改了PHP上传图片100M的限制，现在应该是可以开箱即用的。

示例：

```shell
docker run -it --name=lskypro -p 9080:80 -d halcyonazure/lsky-pro-docker:latest
````

## 通过Dockerfile自己编译镜像

该方法是参考了 #256 里面同样需要感谢的大哥的Dockerfile修改来的

1. 下载 [Release](https://github.com/lsky-org/lsky-pro/releases/tag/2.0)里面最新版的zip压缩包解压
2. 在解压缩后的文件夹内创建[000-default.conf](https://raw.githubusercontent.com/HalcyonAzure/lsky-pro-docker/master/000-default.conf)、[Dockerfile](https://raw.githubusercontent.com/HalcyonAzure/lsky-pro-docker/master/Dockerfile)和[entrypoint.sh](https://raw.githubusercontent.com/HalcyonAzure/lsky-pro-docker/master/entrypoint.sh)文件，并分别写入对应内容。
3. 使用`Dockerfile`进行编译进行编译即可。

## Nginx反向代理设置

如果使用Nginx反代并设置了HTTPS的话，会出现图片加载错误的情况，解决办法参考 #317 在32行添加对应代码后即可成功使用

在Docker内可直接执行以下指令来修改文件内容：

```shell
docker exec -it lskypro sed -i '32 a \\\Illuminate\\Support\\Facades\\URL::forceScheme('"'"'https'"'"');' /var/www/html/app/Providers/AppServiceProvider.php
```

# 用Docker-Compose部署的方法
使用MySQL来作为数据库的话可以参考如下配置
```yaml
version: '3'
services:
  lskypro:
    image: halcyonazure/lsky-pro-docker:latest
    restart: unless-stopped
    hostname: lskypro
    container_name: lskypro
    volumes:
      - /data/lsky/lsky-data:/var/www/html
    ports:
      - "9080:80"
    networks:
      - lsky-net

  mysql-lsky:
    image: mysql:5.7.22
    restart: unless-stopped
    # 主机名，可作为子网域名填入安装引导当中
    hostname: mysql-lsky
    # 容器名称
    container_name: mysql-lsky
    # 修改加密规则
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /data/lsky/mysql/data:/var/lib/mysql
      - /data/lsky/mysql/conf:/etc/mysql
      - /data/lsky/mysql/log:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: lAsWjb6rzSzENUYg # 数据库root用户密码
      MYSQL_DATABASE: lsky-data # 给lsky-pro用的数据库名称
    networks:
      - lsky-net

networks:
  lsky-net:
```

在安装的时的Install界面`数据库连接地址`填入`hostname`即可

**Comment by lovebetterworld** [comment]
麻烦问下，docker部署好lskypro后，用nginx加了https证书，只是给LskyPro加了个Https为什么？
图片上传上去后，图片的URL还是http://ip:port这种格式
麻烦问下什么问题？

**Reply by HalcyonAzure** [reply]
这个应该只是Lsky-Pro后台显示链接为`http`，已看见对应该问题的`issues`关闭，且在 #368 那边有对应解决方案

**Comment by sunteta** [comment]
我这边出错

```
[Sat Apr 30 17:14:35.074516 2022] [:crit] [pid 12] (38)Function not implemented: AH00141: Could not initialize random number generator
Action '-D FOREGROUND' failed.
The Apache error log may have more information.
```

Docker-Compose
```
version: '3'
services:
  lskypro:
    image: halcyonazure/lsky-pro-docker:latest
    restart: unless-stopped
    hostname: lskypro
    container_name: lskypro
    volumes:
      - /volume1/docker/lsky/lsky-data:/var/www/html
    ports:
      - "9080:80"
    networks:
      - lsky-net

  mysql-lsky:
    image: mysql:5.7.22
    restart: unless-stopped
    # 主机名，可作为子网域名填入安装引导当中
    hostname: mysql-lsky
    # 容器名称
    container_name: mysql-lsky
    # 修改加密规则
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /volume1/docker/lsky/mysql/data:/var/lib/mysql
      - /volume1/docker/lsky/mysql/conf:/etc/mysql
      - /volume1/docker/lsky/mysql/log:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: lsky # 数据库root用户密码
      MYSQL_DATABASE: lsky # 给lsky-pro用的数据库名称
    networks:
      - lsky-net

networks:
  lsky-net:
```
