### DISCUSSION TITLE
开源版的docker支持

### DISCUSSION THREAD

**Discussion by cuckoo711** [lsky-org/lsky-pro#753] [教程]
### 本机环境（仅供参考）
- 本机运行环境：`Ubuntu 23.10`  `x86_64`  `宝塔8.0.4`
- lksy版本：'lsky-pro-2.1'（从[Releases](https://github.com/lsky-org/lsky-pro/releases)）下载

### 准备文件
1. 在本地任意地方创建一个空文件夹（至少得是docker能访问的文件夹）（我的是放在宝塔的docker项目里，路径：'/www/dk_project/projects/lsky'）
2. 将下载好的 'lsky-pro.zip' 压缩包放在该目录并解压成 'lsky-pro' 文件夹（不要解压到当前目录）
3. 创建 'nginx.conf' （感谢隔壁 [企业版docker部署教程](https://github.com/lsky-org/lsky-pro/discussions/749)，本 'nginx.conf' 引用于此）：
```
worker_processes  1;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    log_format  main_timed  '$remote_addr - $remote_user [$time_local] "$request" '
                            '$status $body_bytes_sent "$http_referer" '
                            '"$http_user_agent" "$http_x_forwarded_for" '
                            '$request_time $upstream_response_time $pipe $upstream_cache_status';

    access_log /dev/stdout main_timed;
    error_log /dev/stderr notice;

    keepalive_timeout 65;

    server_tokens off;

    # Enable gzip compression
    gzip on;
    gzip_disable "msie6";
    gzip_proxied any;

    gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript;

    # Forward the cloudfront scheme from upstream
    map "$http_cloudfront_forwarded_proto$http_x_forwarded_proto" $forwarded_scheme {
         default off;
         "~*(https)" on;
     }

    server {
        listen [::]:80 default_server;
        listen 80 default_server;
        server_name _;

        sendfile off;

        # Increase proxy buffers for large requests
        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;

        # Upload limit
        client_max_body_size 50m;
        client_body_buffer_size 128k;

        # The location of our project's public directory.
        root /var/www/html/public;
        index index.php;

        # redirect server error pages to the static page /50x.html
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /var/lib/nginx/html;
        }

        location = /favicon.ico {
            log_not_found off;
            access_log off;
        }

        location = /robots.txt {
            log_not_found off;
            access_log off;
        }

        # Based on https://docs.lsky.pro/docs/enterprise/v1/quick-start/installation.html#%E7%AC%AC%E4%BA%8C%E6%AD%A5-%E5%87%86%E5%A4%87%E8%BF%90%E8%A1%8C%E7%8E%AF%E5%A2%83
        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;

            #fastcgi_intercept_errors on;
            fastcgi_buffer_size 128k;
            fastcgi_buffers 4 256k;
            fastcgi_busy_buffers_size 256k;

            fastcgi_index index.php;
            fastcgi_pass 127.0.0.1:9000;

            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;

            # Forward the scheme from upstream
            fastcgi_param HTTPS $forwarded_scheme;
        }

        # deny access to . files, for security
        location ~ /\. {
            log_not_found off;
            deny all;
        }
    }
}
```
4. 创建 'supervisord.conf'：
```
[supervisord]
nodaemon=true

[program:nginx]
command=/usr/sbin/nginx -g 'daemon off;'

[program:php-fpm]
command=/usr/local/sbin/php-fpm -F
```
5. 创建 'docker-compose.yml' ：
```
version: '3'

services:
  lksk:
    build: .
    image: lsky
    container_name: lsky-main
    restart: always
    ports:
      - "8090:80"
    volumes:
      # 下一行冒号前面的路径是项目的本地储存路径，图床里的图会存在这里，按自己的需求修改，后面的路径不要动（不过其实动了也没关系，在设置里可以修改路径，这里的设置只是为了更方便在外部查看文件）（建议将这一大坨注释删掉）
      - '/www/dk_project/projects/lsky/app/:/var/www/html/storage/app/'
    depends_on:
      - mysql
    networks:
      - lksk-network

  mysql:
    image: mysql:5.7
    container_name: lsky-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root2233
      MYSQL_DATABASE: lsky
      MYSQL_USER: lskyuser
      MYSQL_PASSWORD: lskypasd
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - lksk-network
    ports:
      - "8091:3306"

networks:
  lksk-network:
    driver: bridge

volumes:
  mysql-data:
```
6. 创建 'dockerfile' :
```
FROM php:8.0-fpm

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
    && apt-get install -y nginx libxml2-dev libonig-dev libmagickwand-dev python3-pip \
    && pip3 install supervisor \
    && docker-php-ext-install bcmath ctype dom fileinfo mbstring pdo tokenizer xml pdo_mysql \
    && pecl install imagick \
    && docker-php-ext-enable imagick pdo_mysql \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini \
    && sed -i 's/^open_basedir\s*=.*/;open_basedir =/' /usr/local/etc/php/php.ini

COPY nginx.conf /etc/nginx/nginx.conf
COPY ./lsky-pro /var/www/html

WORKDIR /var/www/html

RUN chown -R www-data:www-data /var/www/html \
    && find /var/www/html -type d -exec chmod 755 {} \; \
    && find /var/www/html -type f -exec chmod 644 {} \;

EXPOSE 80

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
CMD ["/usr/local/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
```

#### 到这里，如果你的目录结构跟下图一致，那么恭喜你，可以开始构建镜像了：
![image](https://github.com/lsky-org/lsky-pro/assets/136433555/9c0671fe-d6de-41be-9093-1bb42d576f63)

### 创建镜像
1. cd 到这个文件夹
```cd /www/dk_project/projects/lsky```
2. ~~使用docker命令创建镜像 ```docker build -t [镜像名称]:[标签] .``` 注意这后面是有个 ‘.’ 的，表示在当前目录~~
    > ~~docker build -t lsky:2.1 . ~~

    ~~_当然你也可以跳过这一步，直接用 'docker-compose.yml' 创建也行_~~
3. 运行 Docker Compose
- 运行以下命令来启动和运行你在 docker-compose.yml 文件中定义的所有服务：
    ```docker-compose up```
- 如果你想在后台运行服务，可以添加 -d 标志：
    ```docker-compose up -d```
    _这个命令将根据 'docker-compose.yml' 文件中的定义启动服务，如果需要，还会构建任何没有预先构建的镜像（所以第二步可以跳过）_
- 如果你对 'dockerfile' 或 'docker-compose.yml' 文件做了更改，你可以使用以下命令重新构建服务并启动它们
    ```docker-compose up --build```

当构建完成后应该会出现这样的面板（因为我是已经构建过了，镜像都在缓存里所以很快，正常的话会耗点时间）：
![image](https://github.com/lsky-org/lsky-pro/assets/136433555/d0128293-d83d-4818-b0e0-6ef3d60ea2be)

### 开放端口
- 在上面的 'docker-compose.yml' 中我映射了8090端口到宿主机，对应的我需要开启本机的8090端口访问权限
- 用你们系统自带的防火墙也好，宝塔面板的端口管理也好，总之把8090开起来就行，不会的自己百度或者问gpt

### 安装本体
1. 导航到 [服务器ip]:8090 当然你也可以先对它做个反向代理到某个域名，我就不多说了
2. 正常情况下，应该是能直接看到安装界面的（如果噶了的话评论区反馈我瞅瞅）：
![image](https://github.com/lsky-org/lsky-pro/assets/136433555/622a09d4-b9cd-4212-a7ad-cd50b242e876)
3. 对应你的 'docker-compose.yml' 中mysql的链接参数，不要用root不要用root不要用root
![image](https://github.com/lsky-org/lsky-pro/assets/136433555/a1fd80f8-fab6-4460-a2f9-1ae62650b1d9)
4.如果你看到了这样的图，那么恭喜你安装完成了：
![image](https://github.com/lsky-org/lsky-pro/assets/136433555/7fb9d992-870d-42cf-afdf-5380c7bfa9dc)

### 简单配置
1. 首先进行一个登录
![image](https://github.com/lsky-org/lsky-pro/assets/136433555/90b4b9e2-44db-4c42-b310-169eb4e67cfe)
2. 使用刚才安装时的超管账密，可以记住密码，然后登录
![image](https://github.com/lsky-org/lsky-pro/assets/136433555/087ce2d0-68f9-4857-8b23-2260a7660a06)
3. 进入储存策略，编辑
![image](https://github.com/lsky-org/lsky-pro/assets/136433555/bc533d48-0a4f-4274-a526-b2118a328410)
4.我映射的是整个app文件夹，所以在这里的储存路径中只要是app文件夹里的，都会被映射到宿主机
![image](https://github.com/lsky-org/lsky-pro/assets/136433555/d6718650-6167-46d2-9aa6-46a9f3680f27)
